# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: testservice # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  #region: us-east-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  generateimage:
    description: Generates Tama Image
    memorySize: 1536
    timeout: 30
    handler: bin/genimage
    events:
      - http:
          path: img/{pokemon}/{background}/{hp}/{dirt}/{hunger}/{level}/{xp}
          method: get
          request:
            parameters:
              paths:
                pokemon: true
                background: true
                hp: true
                dirt: true
                hunger: true
                level: true
                xp: true
  gentama:
    description: Generates Tama
    memorySize: 1536
    timeout: 30
    handler: bin/genTama.go
    events:
      - http:
          path: genTama/{authID}
          method: get
          request:
            parameters:
              paths:
                authID: true

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

